; Configuration file for RepRapFirmware on Duet 3 Mini 5+ Ethernet
; executed by the firmware on start-up
;
; generated by RepRapFirmware Configuration Tool v3.6.0 on Tue Aug 19 2025 15:22:32 GMT+1000 (Australian Eastern Standard Time)

; General
G90 ; absolute coordinates
M83 ; relative extruder moves
M550 P"Duet 3" ; set hostname
M98 P"pulsar_init.g"

; Network
M552 P172.22.22.100  S1 ; configure Ethernet adapter
M553 P255.255.255.0 ; set netmask
M586 P0 S1 ; configure HTTP
M551 P""                     ; clear/set empty password
M552 S1                      ; enable networking (use S0 to disable, S1 to enable at startup)
M586 P0 S1                   ; enable HTTP
M586 P1 S0                   ; disable FTP
M586 P2 S1                   ; enable Telnet

; Motor Idle Current Reduction
; ---M906 I30 ; set motor current idle factor
; ---M84 S30 ; set motor current idle timeout

; Driver & mapping — extruder is on onboard Drive 1 (driver 0.1) as of
; the re-wire from an external driver that was on 0.4. Flip S if the
; screw spins the wrong direction once you confirm motion.
M569 P0.1 S1 D2                 ; driver 0.1 forward, spreadCycle
M584 E0.1                       ; map extruder to driver 0.1

; Microstepping + steps
M350 E16 I1                     ; 16× + interpolation (Dyze baseline assumes 16×)
M92  E1000                      ; Dyze baseline steps/mm (calibrate later)

; Current & motion (start conservative)
M906 E1200 I30                  ; ~1.2 A RMS, 30% idle (motor rated 1.68 A/phase)
M203 E6000                      ; max feed 6000 mm/min (100 mm/s)
M201 E500                       ; accel 500 mm/s²
M566 E300                       ; jerk 300 mm/min (5 mm/s)

; Quality-of-life while testing
M302 P1                         ; allow cold extrusion (remove in production)
M83                             ; relative extrusion

; Motor is now on the onboard driver at 0.1, so M906 E<current> above
; DOES apply — start at 1200 mA (1.2 A RMS), the onboard driver caps
; around 1.4 A RMS. If the screw stalls under load, push toward 1400.
M906 I30
M84 S30
; ---; Extruders
; ---M584 E5 ; set extruder mapping
; ---M350 E16 I1 ; configure microstepping with interpolation
; ---M906 E1000 ; set extruder driver currents
; ---M92 E1000 ; configure steps per mm
; ---M566 E120 ; set maximum instantaneous speed changes (mm/min)
; ---M203 E180000 ; set maximum speeds (mm/min)
; ---M201 E250 ; set accelerations (mm/s^2)


; --- Sensors ---
M308 S0 P"spi.cs1" Y"rtdmax31865" A"Top"    W2 F50   ; RTD1 = Top
M308 S1 P"spi.cs2" Y"rtdmax31865" A"Bottom" W2 F50   ; RTD2 = Bottom

; --- Heaters (Top on out1 as H0, Bottom on out2 as H1) ---
M950 H0 C"out1" T0                                  ; H0 uses Top sensor
M950 H1 C"out2" T1                                  ; H1 uses Bottom sensor
; Clear heater faults for both heaters on startup
M562 H0:1

; Safety limits (keep these, remove the custom monitors below)
M143 H0 S500
M143 H1 S500

; Heater models (add low PWM freq for AC SSRs)
M307 H0 R1.617 K0.215:0.000 D24.71 E1.35 S0.80 B0
M307 H1 R1.578 K0.253:0.000 D14.99 E1.35 S0.50 B0
; OPTIONAL: relax “temp rising too slowly” for big barrels
M570 H0 P600
M570 H1 P600

; Fans
M950 F0 C"out5" ; create fan #0
M106 P0 S1 L0 X1 B0.1 ; configure fan #0
M950 F1 C"out6" ; create fan #1
M106 P1 S1 L0 X1 B0.1 ; configure fan #1

; Tools
;
; Two bugs, two fixes, in order:
; 1. H0/H1 both listed under one tool's H<list> (`H1:0`) — any scalar-S
;    command that touched either heater (G10, M568, even bare M104 Hn)
;    routed through the tool and broadcast that one S to every heater
;    the tool owned. Confirmed via M409 K"heat.heaters".
; 2. Took H0/H1 off the tool entirely so nothing could broadcast — but
;    then M104 H0/M104 H1 accepted with no error and did nothing; the
;    DWC Tools row showed the heater as "n/a" and neither zone heated.
;    Heaters that belong to no tool never enter the "active" state on
;    this firmware.
; 3. Gave each zone its own single-heater tool, set via G10 Pn Sn Rn —
;    but G10 only writes target values, it doesn't change the heater's
;    off/standby/active state. Without T-selecting the tool, the heater
;    sat in standby: M116 Pn saw nothing pending and returned instantly.
;
; Fix: same one-heater-per-tool split, but set/activate via M568 Pn ...
; A2 instead of G10 — the A parameter explicitly forces "active" state
; without needing to T-select the tool. Safe here (no broadcast risk)
; because each tool owns exactly one heater. Tool 0 keeps the extruder
; drive + fans for extrusion (T0, unrelated to heating).
M563 P0 S"Pulsar" D0 F0:1  ; drive + fans — extrusion only, no heaters
M563 P1 S"Barrel" H0      ; owns H0 (Top) only
M563 P2 S"Nozzle" H1      ; owns H1 (Bottom) only
; S0 R0 initialises the active/standby setpoints to 0 so a fresh boot
; shows a clean "0 / 0" in DWC. Without them the setpoints default to
; -273.15 ("unset"), which is harmless — pulsar_preheat overwrites them
; — but looks alarming. A0 forces the heater to the off state.
M568 P1 S0 R0 A0 ; barrel heater off, setpoints zeroed
M568 P2 S0 R0 A0 ; nozzle heater off, setpoints zeroed
M302 P1                        ; allow extrusion regardless of temperature

M584                         ; no axes defined
M564 S0 H0                   ; allow moves without homing, ignore homing requirement
